-- Import données oeuvres (colonne titre)

INSERT IGNORE INTO `oeuvres` (`id`, `titre`) VALUES
(1, 'La Joconde'),
(2, 'La Nuit étoilée'),
(3, 'Le Cri'),
(4, 'La Jeune Fille à la perle'),
(5, 'La Naissance de Vénus'),
(6, 'Les Ménines'),
(7, 'La Liberté guidant le peuple'),
(8, 'Le Déjeuner sur l\'herbe'),
(9, 'Impression, soleil levant'),
(10, 'Les Tournesols'),
(11, 'La Grande Vague de Kanagawa'),
(12, 'American Gothic'),
(13, 'Le Baiser'),
(14, 'La Création d\'Adam'),
(15, 'Le Radeau de la Méduse'),
(16, 'La Laitière'),
(17, 'Les Époux Arnolfini'),
(18, 'Le Serment des Horaces'),
(19, 'La Mort de Marat'),
(20, 'Le Jardin des délices'),
(21, 'Nighthawks'),
(22, 'Temple Antique'),
(23, 'Le Voyageur contemplant une mer de nuages'),
(24, 'La Mort et le Fossoyeur'),
(25, 'L\'Île des morts'),
(26, 'The Burning of the Houses of Parliament'),
(27, 'Sunset Near Overschie'),
(28, 'The Fog Warning'),
(29, 'Les Amants'),
(30, 'Guernica'),
(31, 'Les Demoiselles d\'Avignon'),
(32, 'Le Grand Masturbateur'),
(33, 'La Persistance de la mémoire'),
(34, 'Massacre en Corée'),
(35, 'Le Fils de l\'homme'),
(36, 'Golconde'),
(37, 'Le Trois Mai 1808'),
(38, 'Ceci n\'est pas une pipe'),
(39, 'Campbell\'s Soup Cans'),
(40, 'Marilyn Diptych'),
(41, 'Eight Elvises'),
(42, 'Femme assise près d\'une fenêtre'),
(43, 'Autoportrait à l\'oreille bandée'),
(44, 'Terrasse du café le soir'),
(45, 'Champ de blé aux corbeaux'),
(46, 'La Chambre à Arles'),
(47, 'Le Moulin de la Galette'),
(48, 'Paris Street, Rainy Day'),
(49, 'Le Déjeuner des canotiers'),
(50, 'The Singing Butler'),
(51, 'La Gare Saint-Lazare'),
(52, 'La Tour des chevaux bleus'),
(53, 'Les Coquelicots'),
(54, 'Le Christ dans la tempête sur la mer de Galilée'),
(55, 'Saturne dévorant un de ses fils');