-- --------------------------------------------------------
-- Table : sculptures
-- --------------------------------------------------------

CREATE TABLE IF NOT EXISTS `sculptures` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nom_sculpture` VARCHAR(255) NOT NULL,
  `auteur` VARCHAR(255) DEFAULT NULL,
  `date` VARCHAR(100) DEFAULT NULL,
  `musee_actuel` VARCHAR(255) DEFAULT NULL,
  `materiau` VARCHAR(255) DEFAULT NULL,
  `hauteur` VARCHAR(100) DEFAULT NULL,
  `poids` VARCHAR(100) DEFAULT NULL,
  `mouvement_artistique` VARCHAR(255) DEFAULT NULL,
  `particularite` TEXT DEFAULT NULL,
  `descriptif` TEXT DEFAULT NULL,
  `modele_3d_disponible` TINYINT(1) NOT NULL DEFAULT 0,
  `modele_3d_chemin` VARCHAR(255) DEFAULT NULL,
  `image_url` VARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------
-- Données
-- --------------------------------------------------------

INSERT INTO `sculptures` (`id`, `nom_sculpture`, `auteur`, `date`, `musee_actuel`, `materiau`, `hauteur`, `poids`, `mouvement_artistique`, `particularite`, `descriptif`, `modele_3d_disponible`, `modele_3d_chemin`) VALUES
(1, 'Vénus de Milo', 'Probablement Alexandros d\'Antioche', 'vers 130–100 av. J.-C.', 'Musée du Louvre - Paris', 'Marbre', '2,04 m', 'environ 900 kg', 'Art hellénistique', 'Ses bras manquants ont contribué à sa renommée mondiale.', 'Découverte en 1820 sur l\'île grecque de Milos, la Vénus de Milo représente probablement la déesse Aphrodite. Chef-d\'œuvre de la sculpture hellénistique, elle est célébrée pour l\'idéal de beauté féminine qu\'elle incarne, malgré — ou grâce à — ses bras manquants qui alimentent depuis deux siècles les hypothèses des historiens de l\'art.', 1, 'res/assets/3d/model_sculpture/Venus_de_milos.glb'),
(2, 'Victoire de Samothrace', 'Artiste inconnu', 'vers 190 av. J.-C.', 'Musée du Louvre - Paris', 'Marbre', '5,57 m (avec le socle en forme de proue)', 'plusieurs tonnes', 'Art hellénistique', 'Donne une impression saisissante de mouvement malgré l\'absence de tête et de bras.', 'Érigée pour célébrer une victoire navale grecque, probablement celle de Rhodes sur Antiochos III, la Victoire de Samothrace représente la déesse Niké se posant sur la proue d\'un navire. Ses ailes déployées et ses drapés agités par le vent en font l\'un des exemples les plus spectaculaires du dynamisme dans la sculpture antique.', 1, 'res/assets/3d/model_sculpture/Victoire_de_samothrace.glb'),
(3, 'Le Penseur', 'Auguste Rodin', 'conçu en 1880, premiers bronzes au début du XXᵉ siècle', 'Musée Rodin - Paris', 'Bronze', 'environ 1,89 m (grand modèle)', 'environ 600 à 700 kg selon les fontes', 'Impressionnisme / Symbolisme', 'Initialement conçu pour faire partie de La Porte de l\'Enfer avant de devenir une œuvre autonome.', 'Initialement pensé comme une représentation de Dante méditant devant les portes de l\'Enfer, Le Penseur est devenu le symbole universel de la réflexion et de la philosophie. Rodin a travaillé la composition sur plusieurs années à partir de 1880, créant une figure dont la posture tendue traduit un effort intellectuel intense. De nombreuses fontes ont été réalisées ; l\'exemplaire du Musée Rodin est l\'un des plus connus.', 1, 'res/assets/3d/model_sculpture/le_penseur_rodin.glb'),
(4, 'David', 'Michel-Ange', '1501–1504', 'Galleria dell\'Accademia - Florence', 'Marbre de Carrare', '5,17 m', 'environ 6 tonnes', 'Renaissance italienne', 'Célèbre pour son réalisme anatomique exceptionnel et sa représentation du héros juste avant le combat.', 'Commandé par la République de Florence, le David de Michel-Ange représente le héros biblique juste avant son affrontement avec Goliath. Réalisé dans un bloc de marbre considéré comme ingérable par d\'autres sculpteurs, il est devenu un symbole de la perfection du corps humain et de l\'idéal humaniste de la Renaissance. Sa tension musculaire et son regard concentré en font l\'une des œuvres les plus étudiées de l\'histoire de l\'art.', 1, 'res/assets/3d/model_sculpture/david_michelangelo.glb'),
(5, 'La Pietà', 'Michel-Ange', '1498–1499', 'Basilique Saint-Pierre - Vatican', 'Marbre', '1,74 m', 'plusieurs tonnes', 'Renaissance italienne', 'Seule œuvre signée par Michel-Ange, réalisée alors qu\'il avait une vingtaine d\'années.', 'Commandée par le cardinal français Jean de Bilhères, la Pietà représente la Vierge Marie tenant dans ses bras le corps du Christ après la crucifixion. Réalisée par Michel-Ange alors qu\'il n\'avait qu\'une vingtaine d\'années, l\'œuvre stupéfia ses contemporains par sa maîtrise technique. Il s\'agit de la seule sculpture que l\'artiste ait jamais signée, son nom étant gravé sur la bandoulière de la Vierge.', 0, NULL),
(6, 'Psyché ranimée par le baiser de l\'Amour', 'Antonio Canova', '1787–1793', 'Musée du Louvre - Paris', 'Marbre blanc', 'environ 1,55 m', 'non documenté avec précision', 'Néoclassicisme', 'Composition très dynamique et délicate, sommet du néoclassicisme.', 'Inspirée de la mythologie gréco-romaine, cette sculpture représente Cupidon réveillant Psyché d\'un baiser après qu\'elle s\'est évanouie en ouvrant la boîte d\'Hadès. Commandée en 1787 par le colonel John Campbell, l\'œuvre fut achevée en 1793. Canova y atteint un équilibre remarquable entre sensualité et légèreté, transformant le marbre en matière presque immatérielle.', 1, 'res/assets/3d/model_sculpture/psyche_revived_by_cupid.glb'),
(7, 'Le Scribe accroupi', 'Artiste inconnu', 'vers 2600–2350 av. J.-C.', 'Musée du Louvre - Paris', 'Calcaire peint, yeux incrustés de cristal de roche et cuivre', '53,7 cm', 'quelques dizaines de kilogrammes', 'Art égyptien antique (Ancien Empire)', 'Regard extrêmement réaliste grâce aux incrustations des yeux en cristal de roche.', 'Statue funéraire égyptienne de l\'Ancien Empire, le Scribe accroupi représente un fonctionnaire en position de travail, prêt à écrire. Son regard d\'une intensité saisissante, obtenu grâce à des yeux incrustés de cristal de roche, de calcite et de cuivre, lui confère une présence presque vivante. C\'est l\'une des sculptures égyptiennes antiques les plus admirées pour son réalisme et son expression.', 0, NULL),
(8, 'Apollon du Belvédère', 'D\'après un original grec attribué à Léocharès', 'copie romaine du IIᵉ siècle ap. J.-C.', 'Musées du Vatican - Rome', 'Marbre', '2,24 m', 'estimé à plus d\'une tonne', 'Art grec classique / Art romain', 'Longtemps considéré comme l\'idéal absolu de la beauté classique en Europe.', 'Copie romaine d\'un original grec en bronze aujourd\'hui disparu, attribué au sculpteur Léocharès, l\'Apollon du Belvédère représente le dieu solaire dans une posture de majesté sereine. Redécouvert à la fin du XVᵉ siècle, il devint rapidement la référence absolue de la beauté idéale pour les artistes et théoriciens de la Renaissance et du néoclassicisme. Winckelmann le décrivit comme le plus haut idéal de l\'art antique.', 1, 'res/assets/3d/model_sculpture/apollon_du_belvedere.glb'),
(9, 'Discobole', 'Myron (original) — copies romaines anonymes', 'original vers 460–450 av. J.-C.', 'Plusieurs copies exposées dans différents musées', 'Marbre (copies romaines) — Bronze (original perdu)', 'environ 1,55 m', 'variable selon la copie', 'Art grec classique (période sévère)', 'Célèbre pour son équilibre parfait et sa représentation du mouvement au sommet de son élan.', 'Créé par le sculpteur grec Myron vers 450 av. J.-C., le Discobole représente un athlète au moment précis où il s\'apprête à lancer son disque. L\'original en bronze est perdu, mais plusieurs copies romaines en marbre en conservent l\'esprit. L\'œuvre est pionnière dans la représentation du mouvement et de l\'anatomie en tension, et reste l\'un des symboles de l\'idéal sportif et esthétique grec.', 1, 'res/assets/3d/model_sculpture/discobolus.glb'),
(10, 'L\'Esclave mourant', 'Michel-Ange', '1513–1516', 'Musée du Louvre - Paris', 'Marbre', '2,29 m', 'plusieurs tonnes', 'Renaissance italienne (Maniérisme naissant)', 'Expression ambiguë entre souffrance et sérénité, l\'une des œuvres les plus admirées de la Renaissance.', 'Réalisé pour le projet grandiose du tombeau du pape Jules II, finalement remanié plusieurs fois, l\'Esclave mourant de Michel-Ange fascine par l\'ambiguïté de son expression : le visage semble osciller entre la douleur et un abandon presque serein. Cette tension entre le corps contraint et l\'âme qui se libère est au cœur du style de Michel-Ange. L\'œuvre entra dans les collections françaises au XVIᵉ siècle et est conservée au Louvre depuis la Révolution.', 0, NULL),
(11, 'Buste de Néfertiti', 'Thoutmôsis', 'vers 1345 av. J.-C.', 'Neues Museum - Berlin', 'Calcaire et stuc peint', '48 cm', 'non documenté', 'Art égyptien antique (période amarnienne)', 'Célèbre pour son réalisme et son exceptionnel état de conservation.', 'Le buste de Néfertiti représente l\'épouse du pharaon Akhenaton, qui régna au XIVᵉ siècle av. J.-C. Réalisé dans l\'atelier du sculpteur Thoutmôsis, il servait probablement de modèle pour d\'autres portraits royaux. Redécouvert en 1912 lors de fouilles archéologiques à Amarna, il est devenu l\'un des symboles les plus célèbres de l\'art égyptien grâce à son incroyable finesse et à son état de conservation exceptionnel.', 1, 'res/assets/3d/model_sculpture/buste_nefertiti.glb'),
(12, 'Louve capitoline', 'Artiste inconnu', 'probablement entre le Vᵉ et le XIIIᵉ siècle', 'Musées du Capitole - Rome', 'Bronze', 'environ 75 cm', 'non documenté', 'Art romain antique / Art médiéval (débattu)', 'Représente la louve allaitant Romulus et Rémus, symbole fondateur de Rome.', 'Selon la légende romaine, la louve recueillit et allaita les jumeaux Romulus et Rémus après leur abandon sur les rives du Tibre. Les deux frères auraient ensuite fondé la ville de Rome. La sculpture est devenue un emblème de la capitale italienne et symbolise la naissance mythique de la civilisation romaine.', 0, NULL),
(13, 'Laocoon et ses fils', 'Attribué à trois sculpteurs de Rhodes', 'Iᵉʳ siècle av. J.-C. ou Iᵉʳ siècle ap. J.-C.', 'Musées du Vatican - Rome', 'Marbre', 'environ 2,4 m', 'plusieurs tonnes', 'Art hellénistique', 'Chef-d\'œuvre illustrant le drame et le mouvement de l\'art hellénistique.', 'Cette sculpture illustre un épisode de la guerre de Troie : le prêtre troyen Laocoon avertit ses compatriotes de ne pas faire entrer le cheval de bois dans la ville. Pour le faire taire, les dieux envoient deux serpents géants qui étranglent Laocoon et ses deux fils. Découverte à Rome en 1506, l\'œuvre impressionna profondément les artistes de la Renaissance, notamment Michel-Ange.', 0, NULL),
(14, 'Le Gaulois mourant', 'Artiste inconnu (copie romaine)', 'copie romaine du IIᵉ siècle', 'Musées du Capitole - Rome', 'Marbre', 'environ 1,80 m (longueur)', 'plusieurs tonnes', 'Art hellénistique / Art romain', 'Représente un guerrier vaincu avec une grande dignité, symbole universel de noblesse face à la défaite.', 'Cette statue représente un guerrier celte blessé à mort après une bataille contre les Grecs. Plutôt que de montrer un ennemi humilié, le sculpteur le dépeint avec noblesse et courage dans ses derniers instants. L\'œuvre est devenue un symbole universel de la dignité face à la défaite.', 1, 'res/assets/3d/model_sculpture/le_gaulois_mourant.glb'),
(15, 'Hermès portant Dionysos enfant', 'Attribué à Praxitèle', 'vers 340 av. J.-C.', 'Musée archéologique d\'Olympie - Olympie', 'Marbre', 'environ 2,13 m', 'plusieurs tonnes', 'Art grec classique (période tardive)', 'L\'une des sculptures grecques les mieux conservées.', 'Dans la mythologie grecque, Hermès reçoit la mission de protéger le jeune Dionysos après la mort de sa mère. La sculpture montre le dieu messager portant l\'enfant tout en le divertissant avec une grappe de raisin. Son élégance et son naturel en font l\'une des œuvres les plus admirées de la sculpture grecque classique.', 0, NULL),
(16, 'Vénus Médicis', 'Artiste inconnu', 'Iᵉʳ siècle av. J.-C.', 'Galerie des Offices - Florence', 'Marbre', 'environ 1,53 m', 'plus d\'une tonne', 'Art grec classique / Art romain', 'Considérée comme un modèle idéal de beauté féminine, très admirée à la Renaissance.', 'Cette statue représente Aphrodite (Vénus chez les Romains) au moment où elle tente pudiquement de cacher sa nudité après être sortie de la mer. Très admirée à la Renaissance, elle inspira de nombreux artistes européens et contribua à diffuser l\'idéal de beauté antique à travers toute l\'Europe.', 1, 'res/assets/3d/model_sculpture/venus_medicis.glb'),
(17, 'Hermaphrodite endormi', 'Artiste inconnu', 'IIᵉ siècle ap. J.-C.', 'Musée du Louvre - Paris', 'Marbre', 'environ 1,70 m (longueur)', 'plusieurs tonnes', 'Art romain impérial', 'Connu pour son illusion visuelle surprenante selon l\'angle d\'observation.', 'Inspirée de la mythologie grecque, cette sculpture représente Hermaphrodite, enfant d\'Hermès et d\'Aphrodite, dont le corps réunit des caractéristiques masculines et féminines. Vue de dos, elle semble représenter une femme endormie ; en s\'approchant, le visiteur découvre une anatomie inattendue, créant un effet de surprise voulu par l\'artiste.', 0, NULL),
(18, 'Le Boxeur au repos', 'Artiste inconnu', 'IVᵉ siècle av. J.-C.', 'Musée national romain - Rome', 'Bronze', 'environ 1,28 m', 'non documenté', 'Art grec hellénistique', 'Rare bronze antique conservé presque intact, d\'un réalisme saisissant.', 'Cette sculpture en bronze montre un boxeur assis après un combat éprouvant. Son visage porte les marques des coups, avec des cicatrices et des oreilles déformées typiques des athlètes de l\'époque. L\'œuvre est remarquable pour son réalisme et son humanité, loin des représentations idéalisées des héros antiques.', 0, NULL),
(19, 'Aphrodite de Cnide', 'Praxitèle', 'original vers 360 av. J.-C.', 'Musées du Vatican - Rome (copie célèbre)', 'Marbre (copies romaines)', 'non documentée avec précision', 'non documenté', 'Art grec classique (période tardive)', 'Première grande statue grecque représentant une déesse entièrement nue.', 'Créée par Praxitèle au IVᵉ siècle av. J.-C., cette statue fut la première représentation monumentale d\'une déesse grecque entièrement nue. Elle montre Aphrodite juste avant son bain, dans une posture à la fois naturelle et pudique. L\'original ayant disparu, seules des copies romaines permettent aujourd\'hui d\'en admirer les formes.', 0, NULL),
(20, 'Niké de Paionios', 'Paionios de Mendè', 'vers 420 av. J.-C.', 'Musée archéologique d\'Olympie - Olympie', 'Marbre', 'environ 2 m (statue seule)', 'plusieurs tonnes', 'Art grec classique', 'Effet de mouvement remarquable représentant la déesse descendant du ciel.', 'Cette statue représente Niké, la déesse grecque de la Victoire, descendant du ciel pour annoncer un triomphe militaire. Érigée à Olympie au Vᵉ siècle av. J.-C., elle était perchée sur une haute colonne afin de donner l\'impression qu\'elle volait au-dessus des visiteurs. Les plis de son vêtement et la position de son corps créent un effet de mouvement particulièrement spectaculaire.', 0, NULL),
(21, 'Buste de Jules César', 'Artiste inconnu (sculpture romaine)', 'vers 44–30 av. J.-C.', 'Musée archéologique de Turin - Turin', 'Marbre', 'environ 50 cm', 'quelques dizaines de kilogrammes', 'Art romain (portrait réaliste)', 'L\'un des portraits les plus ressemblants du dictateur romain, réalisé peu après son assassinat.', 'Ce buste représente Caius Julius Caesar (100–44 av. J.-C.), général, homme d\'État et écrivain romain qui joua un rôle décisif dans la transformation de la République romaine en Empire. Il est réalisé dans la tradition du portrait romain réaliste, avec des traits marqués et une expression de détermination. De nombreux bustes furent réalisés de son vivant et après son assassinat aux Ides de Mars, perpétuant l\'image du dictateur.', 1, 'res/assets/3d/model_sculpture/buste_jules_cesar.glb'),
(22, 'Les Bourgeois de Calais', 'Auguste Rodin', '1889', 'Musée Rodin - Paris (exemplaire principal)', 'Bronze', 'environ 2,10 m (groupe)', 'plusieurs tonnes', 'Impressionnisme / Symbolisme', 'Plusieurs fontes existent, exposées dans de nombreuses villes à travers le monde.', 'Cette œuvre monumentale commémore un épisode de la guerre de Cent Ans : en 1347, six bourgeois de Calais se sacrifièrent pour sauver leur ville assiégée par le roi d\'Angleterre Édouard III. Rodin rompt avec la tradition héroïque en représentant les six hommes à égalité, accablés et résignés plutôt que triomphants. La composition, sans socle surélevé, place les personnages au niveau du spectateur pour accentuer l\'émotion.', 1, 'res/assets/3d/model_sculpture/les_bourgeois_de_calais.glb'),
(23, 'Lion assis', 'Artiste inconnu', 'époque non déterminée', 'Collection diverse', 'Pierre ou marbre', 'variable', 'non documenté', 'Art antique (Grèce / Rome / Égypte)', 'Symbole de puissance et de royauté présent dans de nombreuses civilisations antiques.', 'La représentation du lion assis est l\'une des formes sculpturales les plus répandues dans l\'histoire de l\'art, des sphinx égyptiens aux lions gardiens des temples grecs et romains. Symbole universel de force, de majesté et de protection, ces sculptures ornaient les entrées des palais, des temples et des tombeaux pour en marquer la grandeur et en assurer la garde.', 1, 'res/assets/3d/model_sculpture/lion_assis.glb'),
(24, 'L\'Âge d\'airain', 'Auguste Rodin', '1876–1877', 'Musée Rodin - Paris', 'Bronze', 'environ 1,80 m', 'environ 300 kg', 'Impressionnisme / Réalisme', 'Si réaliste que Rodin fut accusé d\'avoir moulé directement sur un modèle vivant.', 'L\'Âge d\'airain est la première grande sculpture de Rodin, réalisée entre 1876 et 1877. Elle représente un homme nu debout, dans une posture d\'éveil et d\'émergence. Son réalisme anatomique exceptionnel provoqua un scandale : Rodin fut accusé d\'avoir utilisé un surmoulage sur nature, ce qu\'il réfuta en produisant des photographies de son modèle, le soldat belge Auguste Neyt. L\'œuvre symbolise le réveil de l\'humanité et l\'émergence de la conscience.', 1, 'res/assets/3d/model_sculpture/lage_dairain_rodin.glb');
